//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interviewee
    {
        public string Mail { get; set; }
        public int PhoneNumber { get; set; }
        public Nullable<int> Marks { get; set; }
        public int JobID { get; set; }
    
        public virtual JobRole JobRole { get; set; }
    }
}
